# Generated by Django 4.0 on 2021-12-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youke_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(default='', max_length=255, verbose_name='备注')),
            ],
        ),
    ]
