# Generated by Django 4.0 on 2021-12-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdc_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Mdn_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Myun_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Other_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Qibo_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Total_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Zhibo_VulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(default='0000000000', max_length=128, verbose_name='漏洞编号')),
                ('vul_name', models.CharField(default='默认漏洞', max_length=128, verbose_name='漏洞名称')),
                ('vul_jira', models.CharField(default='默认jira工单', max_length=128, verbose_name='Jira工单编号')),
                ('vul_sendto', models.CharField(default='默认', max_length=128, verbose_name='发送对象')),
                ('vul_fixer', models.CharField(default='默认', max_length=128, verbose_name='整改人员')),
                ('vul_sendtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='发送时间')),
                ('vul_estimatefixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='预计修复时间')),
                ('vul_fixedtime', models.CharField(default='2020-10-10 01:01:00', max_length=128, verbose_name='完成修复时间')),
                ('vul_isfixed', models.IntegerField(default=0, verbose_name='是否修复')),
                ('vul_type', models.IntegerField(default=0, verbose_name='漏洞类型')),
                ('vul_remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='youke_vulmodel',
            name='vul_remarks',
            field=models.CharField(max_length=255, verbose_name='备注'),
        ),
    ]
