# Generated by Django 4.0 on 2021-12-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulList', '0002_mdc_vulmodel_mdn_vulmodel_myun_vulmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youke_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
    ]
