# Generated by Django 4.0 on 2021-12-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulList', '0003_alter_youke_vulmodel_vul_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdc_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='mdn_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='myun_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='other_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='qibo_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='total_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='zhibo_vulmodel',
            name='vul_remarks',
            field=models.CharField(default='--', max_length=128, verbose_name='备注'),
        ),
    ]
