# Generated by Django 4.0 on 2021-12-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulList', '0004_alter_mdc_vulmodel_vul_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_vulsRiseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(default='1/1', max_length=128, verbose_name='日期')),
                ('vuls_amount', models.IntegerField(default=0, verbose_name='漏洞数量')),
            ],
        ),
    ]
