# Generated by Django 4.0 on 2021-12-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulList', '0005_total_vulsrisemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_vulsFixModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(default='1/1', max_length=128, verbose_name='日期')),
                ('fixed_amount', models.IntegerField(default=0, verbose_name='已整改漏洞')),
                ('fixing_amount', models.IntegerField(default=0, verbose_name='未整改漏洞')),
            ],
        ),
    ]
